config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  #get 'tags/:tag', to: 'topics#index', as: :tag

  devise_for :users
  
  resources :users, only: [:show, :create, :destroy]


  resources :bookmarks


  resources :tags 
  
  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :history

  acts_as_taggable_on :tags


  #belongs_to :topic
  belongs_to :user
  
  
  validates :name, presence: true, length: {minimum: 1}
  validates :user, presence: true
  validates :url, length: {minimum: 1}

  default_scope {order('created_at DESC')}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookmarks, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :authenticate_user!
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    #@bookmarks = Bookmark.tagged_with(params[:tag])
    @bookmarks = Bookmark.all
  end
   
  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark, notice: "#{@bookmark.name} was created!"
    else
      flash.now[:error] = "Bookmark was not created, please try again"
      render :new
    end
  end

  def edit
  end

  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: "#{@bookmark.name} was updated!"
    else
      flash.now[:error] = "Bookmark was not updated, please try again"
      render :edit
    end
  end

  def destroy
    if @bookmark.destroy
      redirect_to user_path, notice: "#{@bookmark.name} was destroyed!"
    else
      flash[:error] = "Bookmarks was not destroyed, please try again"
      redirect_to user_path
    end
  end

  

  private

  def bookmark_params
    params.require(:bookmark).permit!
  end

  def set_bookmark
    @bookmark = Bookmark.friendly.find(params[:id])
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    # puts "INCOMING PARAMS HERE: #{params}"

    # You put the message-splitting and business
    # magic here. 
    # match_header('subject', '#')

    @user = User.find_by(email: params[:from])
    @bookmark = Bookmark.new(name: params[:subject], url: params['stripped-text'])
    @bookmark.user = @user
    if @bookmark.save
      # Assuming all went well. 
      head 200
    else
      head 404
    end
  end
end

app/controllers/incomming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    puts "INCOMING PARAMS HERE: #{params}"

    # You put the message-splitting and business
    # magic here. 
    match_header('subject', '#')

    # @user = User.find_by(email: from)
    # @bookmark = Bookmark.new(url: subject, tag_list: body)
    # @bookmark.save

    # Assuming all went well. 
    head 200
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  #before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    #binding.pry
    @tags = ActsAsTaggableOn::Tag.all
    #@bookmarks = Bookmark.all
  end

  # @tags.each do |tag|
  #   = link_to tag.name, tag
  #   tag.taggings.map(&:taggable).each do |bookmark|
  #     = link_to bookmark.name, bookmark

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    # @bookmarks = Bookmark.tagged_with(params[:id])
    #@bookmarks = @topic.bookmarks.tagged_with(params[:tag])
    #@bookmarks = @tag.bookmarks
   
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to @tag, notice: "#{@tag.name} was created!"
    else
      flash.now[:error] = "Topic was not created, please try again"
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    #@topic = Topic.friendly.find(params[:id])
    #@bookmarks = @user.bookmarks.order('topic_id DESC').paginate(:page => params[:page], :per_page => 10)
    @bookmarks = @user.bookmarks
    #@tag = ActsAsTaggableOn::Tag.find(params[:id])
    #@bookmarks = @tag.user.bookmarks
  end

  def update
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  #include ActsAsTaggableOn::TagsHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="col-md-3">
  <div class="thumbnail">
    <img src="http://placehold.it/300x200">
    <div class="caption">
      <h3><%= link_to bookmark.name, bookmark %></h3>
      <p>url: <%= bookmark.url %></p>
      <p><%= link_to 'edit', edit_bookmark_path(bookmark) %></p>
      <p><%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: {confirm: 'Really?'} %></p>
      <% if bookmark.tags.any? %>
        <% bookmark.tags.each do |tag| %>
          <p>tag: <%= link_to tag.name %></p>
        <% end %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<%= form_for(bookmark) do |f| %>
  <%= render partial: 'shared/errors', locals: {obj: @bookmark} %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit <%= @bookmark.name %></h1>
<hr>

<%= render partial: 'form', locals: {bookmark: @bookmark} %>

app/views/bookmarks/index.html.erb
<h1>Index View</h1>
<hr>

<div class="row">
  <%= render @bookmarks %>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<hr>

<%= render partial: 'form', locals: {bookmark: @bookmark} %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.name %></h1>
<hr>

<h3><%= @bookmark.name %></h3>
<h3><%= @bookmark.url %></h3>
<p><%= link_to 'edit', edit_bookmark_path(@bookmark) %></p>
<p><%= link_to 'delete', bookmark_path(@bookmark), method: :delete, data: {confirm: 'Really?'} %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeMarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'shared/nav' %>

  <div class="container">

    <%= render 'shared/flash' %>

  <%= yield %>

  </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeMarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <div class="container">

    <%= render 'shared/flash' %>

    <%= yield %>

  </div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Well done!</strong> <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Heads up!</strong> <%= flash[:alert] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Warning!</strong> <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'RecipeMarks', root_path,  class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Tags', tags_path %></li>
        <li><%#= link_to 'New Topic', new_topic_path %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path %></li>
        <li><%= link_to 'New Bookmark', new_bookmark_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">  
        <% if current_user %>
          <li class="dropdown">
            <%= link_to 'My Bookmarks', current_user %>
          </li>
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
           
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tags/_form.html.erb
<%= form_for(topic) do |f| %>
  <%= render partial: 'shared/errors', locals: {obj: @topic} %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div class="row">
  <h3>#<%= link_to tag.name, tag %><small> has <%= bookmarks.count %> bookmarks</small></h3>
  <%#= render bookmarks %>
</div>

app/views/tags/edit.html.erb
<h1>Edit Topics</h1>
<hr>

<%= render partial: 'form', locals: {topic: @topic} %>

app/views/tags/index.html.erb
<h3>Tags</h3>
<hr>
<% @tags.each do |tag| %>
  <h3>#<%= link_to tag.name, tag_path(tag) %></h3>
  <div class="row">
    <% tag.taggings.map(&:taggable).each do |bookmark| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <img src="http://placehold.it/300x200">
          <div class="caption">
            <h3><%= link_to bookmark.name, bookmark %></h3>
            <p>url: <%= bookmark.url %></p>
            <p><%= link_to 'edit', edit_bookmark_path(bookmark) %></p>
            <p><%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: {confirm: 'Really?'} %></p>
            <% if bookmark.tags.any? %>
              <% bookmark.tags.each do |tag| %>
                <p>tag: <%= link_to tag.name %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<!-- <div id="infinite-scrolling">
  <%#= will_paginate @topics, renderer: BootstrapPagination::Rails %>
</di> -->

app/views/tags/new.html.erb
<h1>New Topic</h1>
<hr>

<%= render partial: 'form', locals: {topic: @topic} %>

app/views/tags/show.html.erb
<h1>#<%= @tag.name %></h1>
<hr>

<div class="row">
    <% @tag.taggings.map(&:taggable).each do |bookmark| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <img src="http://placehold.it/300x200">
          <div class="caption">
            <h3><%= link_to bookmark.name, bookmark %></h3>
            <p>url: <%= bookmark.url %></p>
            <p><%= link_to 'edit', edit_bookmark_path(bookmark) %></p>
            <p><%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: {confirm: 'Really?'} %></p>
            <% if bookmark.tags.any? %>
              <% bookmark.tags.each do |tag| %>
                <p>tag: <%= link_to tag.name %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>



<%#= will_paginate @bookmarks, renderer: BootstrapPagination::Rails %>

app/views/users/show.html.erb
<h1><%= @user.email %>'s Bookmarks</h1>
<hr>

<div class="row">
  <%= render @bookmarks %>

  <%# @bookmarks.group_by{ |bookmark| bookmark.topic}.each do |topic, bookmarks| %>
    <%#= render partial: 'topics/topic', object: topic, locals: { bookmarks: bookmarks } %>
  <%# end %>
</div>
  


<%#= will_paginate @bookmarks, renderer: BootstrapPagination::Rails %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to "Bookmarks", bookmarks_path, class: 'btn btn-primary' %>